### ISSUE TITLE
关于数据集音频

### ISSUE THREAD

**Issue by Aliang-CN** [1595258509/VITS_Japanese#1]
大佬，您好！
可以提供一下数据集音频的下载地址吗？

**Comment by Murlors** [comment]
如果指的是一般的语音数据集的话，可以去找网上现有的开放的语音数据集。\
如果是指特定的一些数据集，需要自己提取。

**Comment by Aliang-CN** [comment]
> 如果指的是一般的语音数据集的话，可以去找网上现有的开放的语音数据集。 如果是指特定的一些数据集，需要自己提取。

好的，多谢大佬！还有一个问题，你知道，这么模型想量化，应该怎么做呢。

**Comment by Murlors** [comment]
这方面不是很清楚

**Comment by Aliang-CN** [comment]
> 这方面不是很清楚

好的，多谢大佬！
